require_relative 'json_schema/base'
require_relative 'json_schema/array'
require_relative 'json_schema/boolean'
require_relative 'json_schema/null'
require_relative 'json_schema/number'
require_relative 'json_schema/object'
require_relative 'json_schema/string'
