require 'active_support/core_ext/object/deep_dup'
require 'active_support/hash_with_indifferent_access'
require 'active_support/core_ext/hash/indifferent_access'
# require 'active_support/core_ext/hash/deep_merge'

require 'jsf/version'
require 'jsf/core'
require 'jsf/validations'
require 'jsf/base_hash'
require 'jsf/schema'
require 'jsf/forms'